OPENAI_API_KEY="sk-proj-f7bWjmbxjOoHQZiNzmVHT3BlbkFJIF3sLfCVXfajBPUjYs4C"
ASSISTANT_ID="asst_Rfi7FhPCfUXGaOjgNNfWFA8D"
HELPER_ASSISTANT_ID="asst_Bhi6ZsNqHXw3qExd3AHG1Zbr"

ASSISTANT_TITLE="Sourcee"
ENABLED_FILE_UPLOAD_MESSAGE="" 

AUTHENTICATION_REQUIRED="True"

OPENAI_VECTOR_STORE_ID="vs_t88p7EnQ3YkN8KSGwbVCKr6r" 

MANATAL_API_KEY="3eaa82d6707bd0be7acb6d8dbc001d2ab0429d22"

MAKE_API_KEY="1b07de97-ba53-485a-b71b-f293fd887819"
AZURE_OPENAI_ENDPOINT=""
AZURE_OPENAI_KEY=""
[cookie]
expiry_days = 30
key = "some_signature_key"
name = "some_cookie_name"

[credentials]
usernames = {dwastrid = {email = "astrid.dewael@sbiconsulting.be", name = "Astrid", password = "secret"}}

[preauthorized]
emails = ["quinten@nveil.ai"]




